default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  database: myapp_development
  username: project_v_user
  password: password

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: myapp_test
  pool: 5
  username: project_v_user
  password: password