default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  database: lifesaver
  username: lifesaver_user
  password: password

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: lifesaver
  pool: 5
  username: lifesaver_user
  password: password