# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac5e6798d32b8dd2f188472292bd0ebc432703d81c56f20c2332d82faf10a089185f591fa1a344cada904ea73f57fb10afd9b98a2a008e9e32cc5e6302bba670

test:
  secret_key_base: fbdf0e4599dbd595fb519063312fabcad6669e46ec76bd43c94598b4027c995f650f8e9b59c4f81f1d4b205714b610f6d75ad845e49b4182a8c994194bb7dd7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
